name: Alicissimo Fly Fishes
favicon: null
layout_spectrum: 0.7200121216010302
typography_spectrum: 0.7668124190531671
title: 'Outdoor Lifestyle '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6007650904357433
  lightness: 0.8016855367459357
  saturation: 0.4830580640118569
  rhythmicContrast: 0.5667134211398661
purpose: []
