title: 'Outdoor Lifestyle '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.375
  brandStrength: 0.1875
  lightness: 0
  brandColors:
    - '#79766F'
    - '#1F2024'
    - '#545550'
    - '#C1B9B6'
    - '#FFFFFF'
  rhythmicContrast: 0.5667134211398661
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Alicissimo Fly Fishes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0925926
layout_spectrum: 0.7759856
